package jamesxu.androidspan;

enum SpanType {
    BULLET,
    QUOTE,
    UNDERLINE,
    STRIKETHROUGH,
    BGCOLOR,
    FGCOLOR,
    MASKFILTER_EMBOSS,
    SUBSCRIPT,
    STYLE,
    ABSOLUTE_SIZE_SPAN,
    RELATIVE_SIZE_SPAN,
    TEXTAPPEARANCE_SPAN,
    SUPERSCRIPT,
    LOCALE_SPAN,
    SCALEX_SPAN,
    TYPEFACE_SPAN,
    IMAGE_SPAN,
    MASKFILTER_BLUR,
    ALIGNMENT_STANDARD
}
